/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/
#define NO_MAPS
#define NO_PATTERNS
#define NO_PRODUCTS
#define NO_RECORDS
#define NO_MATH
#define NO_CSV
#define NO_IO
#define NO_VDMUTIL
#define NO_VDMUNIT
