/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#ifndef CLASSES_B_H_
#define CLASSES_B_H_

#define VDM_CG

#include "Vdm.h"

//include types used in the class
#include "A.h"
#include "B.h"
#include "distCall.h"
#include "D.h"


/* -------------------------------
 *
 * Quotes
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * values / global const
 *
 --------------------------------- */ 
 
extern TVP numFields_1;


/* -------------------------------
 *
 * The class
 *
 --------------------------------- */ 
 

//class id
#define CLASS_ID_B_ID 1

#define BCLASS struct B*

// The vtable ids
#define CLASS_B__Z1BE1CA1CA 0
#define CLASS_B__Z7callLocEV 1
#define CLASS_B__Z7callRemEV 2
#define CLASS_B__Z1BEV 3

struct B
{
	
/* Definition of Class: 'B' */
	VDM_CLASS_BASE_DEFINITIONS(B);
	 
	VDM_CLASS_FIELD_DEFINITION(B,a_loc);
	VDM_CLASS_FIELD_DEFINITION(B,a_rem);
	VDM_CLASS_FIELD_DEFINITION(B,numFields);

};


/* -------------------------------
 *
 * Constructors
 *
 --------------------------------- */ 
 

	/* B.vdmrt 9:8 */
	TVP _Z1BE1CA1CA(BCLASS this_, TVP a1, TVP a2);
	/* B.vdmrt 1:7 */
	TVP _Z1BEV(BCLASS this_);


/* -------------------------------
 *
 * public access functions
 *
 --------------------------------- */ 
 
	void B_const_init();
	void B_const_shutdown();
	void B_static_init();
	void B_static_shutdown();


/* -------------------------------
 *
 * Internal
 *
 --------------------------------- */ 
 

void B_free_fields(BCLASS);
BCLASS B_Constructor(BCLASS);



#endif /* CLASSES_B_H_ */