/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#ifndef CLASSES_World_H_
#define CLASSES_World_H_

#define VDM_CG

#include "Vdm.h"

//include types used in the class
#include "B.h"
#include "D.h"
#include "World.h"
#include "distCall.h"
#include "D.h"


/* -------------------------------
 *
 * Quotes
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * values / global const
 *
 --------------------------------- */ 
 
extern TVP numFields_3;


/* -------------------------------
 *
 * The class
 *
 --------------------------------- */ 
 

//class id
#define CLASS_ID_World_ID 3

#define WorldCLASS struct World*

// The vtable ids
#define CLASS_World__Z3RunEV 0
#define CLASS_World__Z5WorldEV 1

struct World
{
	
/* Definition of Class: 'World' */
	VDM_CLASS_BASE_DEFINITIONS(World);
	 
	VDM_CLASS_FIELD_DEFINITION(World,numFields);

};


/* -------------------------------
 *
 * Constructors
 *
 --------------------------------- */ 
 

	/* World.vdmrt 1:7 */
	TVP _Z5WorldEV(WorldCLASS this_);


/* -------------------------------
 *
 * public access functions
 *
 --------------------------------- */ 
 
	void World_const_init();
	void World_const_shutdown();
	void World_static_init();
	void World_static_shutdown();


/* -------------------------------
 *
 * Internal
 *
 --------------------------------- */ 
 

void World_free_fields(WorldCLASS);
WorldCLASS World_Constructor(WorldCLASS);



#endif /* CLASSES_World_H_ */