/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#ifndef CLASSES_A_H_
#define CLASSES_A_H_

#define VDM_CG

#include "Vdm.h"
#include "World.h"

//include types used in the class
#include "A.h"
#include "World.h"
#include "distCall.h"
#include "D.h"


/* -------------------------------
 *
 * Quotes
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * values / global const
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * The class
 *
 --------------------------------- */ 
 

//class id
#define CLASS_ID_A_ID 0

#define ACLASS struct A*

// The vtable ids
#define CLASS_A__Z7productEII 0
#define CLASS_A__Z1AEV 1

struct A
{
	
/* Definition of Class: 'World' */
	VDM_CLASS_BASE_DEFINITIONS(World);
	 
	VDM_CLASS_FIELD_DEFINITION(World,numFields);

	
/* Definition of Class: 'A' */
	VDM_CLASS_BASE_DEFINITIONS(A);
	 
	VDM_CLASS_FIELD_DEFINITION(A,numFields);

};


/* -------------------------------
 *
 * Constructors
 *
 --------------------------------- */ 
 

	/* A.vdmrt 1:7 */
	TVP _Z1AEV(ACLASS this_);


/* -------------------------------
 *
 * public access functions
 *
 --------------------------------- */ 
 
	void A_const_init();
	void A_const_shutdown();
	void A_static_init();
	void A_static_shutdown();


/* -------------------------------
 *
 * Internal
 *
 --------------------------------- */ 
 

void A_free_fields(ACLASS);
ACLASS A_Constructor(ACLASS);



#endif /* CLASSES_A_H_ */