/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "B.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void B_free_fields(struct B *this)
{
			vdmFree(this->m_B_a_loc);
			vdmFree(this->m_B_a_rem);
	}

static void B_free(struct B *this)
{
	--this->_B_refs;
	if (this->_B_refs < 1)
	{
		B_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z17fieldInitializer1EV()	{

TVP ret_2 = newInt(2)
;

return ret_2;
}


/* B.vdmrt 17:8 */
 static  TVP _Z7callLocEV(BCLASS this)	{
/* B.vdmrt 18:36 */
TVP embeding_1 = newIntGC(2, &embeding_1)
;
/* B.vdmrt 18:38 */
TVP embeding_2 = newIntGC(3, &embeding_2)
;
/* B.vdmrt 18:22 */
TVP ret_3 = DIST_CALL(A, A, GET_FIELD_PTR_GC(B, B, this, a_loc), CLASS_ID_A_ID, 2, CLASS_A__Z7productEII, embeding_1, embeding_2)
;
/* B.vdmrt 18:15 */
return ret_3;
}


/* B.vdmrt 20:8 */
 static  TVP _Z7callRemEV(BCLASS this)	{
/* B.vdmrt 21:35 */
TVP embeding_3 = newIntGC(4, &embeding_3)
;
/* B.vdmrt 21:37 */
TVP embeding_4 = newIntGC(8, &embeding_4)
;
/* B.vdmrt 21:21 */
TVP ret_4 = DIST_CALL(A, A, GET_FIELD_PTR_GC(B, B, this, a_rem), CLASS_ID_A_ID, 2, CLASS_A__Z7productEII, embeding_3, embeding_4)
;
/* B.vdmrt 21:14 */
return ret_4;
}



 void B_const_init()	{

numFields_1 = _Z17fieldInitializer1EV();

return ;
}



 void B_const_shutdown()	{

vdmFree(numFields_1);

return ;
}



 void B_static_init()	{

return ;
}



 void B_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForB  [] ={

{0,0,((VirtualFunctionPointer) _Z1BE1CA1CA),},
{0,0,((VirtualFunctionPointer) _Z7callLocEV),},
{0,0,((VirtualFunctionPointer) _Z7callRemEV),},
{0,0,((VirtualFunctionPointer) _Z1BEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
BCLASS B_Constructor(BCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (BCLASS) malloc(sizeof(struct B));
	}

	if(this_ptr!=NULL)
	{
	
			
		// B init
		this_ptr->_B_id = CLASS_ID_B_ID;
		this_ptr->_B_refs = 0;
		this_ptr->_B_pVTable=VTableArrayForB;

							this_ptr->m_B_a_loc= NULL ;
						this_ptr->m_B_a_rem= NULL ;
			}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	BCLASS ptr=B_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_B_id, &ptr->_B_refs, (freeVdmClassFunction)&B_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* B.vdmrt 9:8 */
 TVP _Z1BE1CA1CA(BCLASS this, TVP a1, TVP a2)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, B);
}
;
/* B.vdmrt 12:10 */
TVP field_tmp_1 = vdmCloneGC(a1, &field_tmp_1)
;

SET_FIELD_PTR_GC(B, B, this, a_loc, field_tmp_1);

vdmFree(field_tmp_1);
/* B.vdmrt 13:10 */
TVP field_tmp_2 = vdmCloneGC(a2, &field_tmp_2)
;

SET_FIELD_PTR_GC(B, B, this, a_rem, field_tmp_2);

vdmFree(field_tmp_2);

return __buf;
}


/* B.vdmrt 1:7 */
 TVP _Z1BEV(BCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, B);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order
	TVP numFields_1 =  NULL ;
			


