/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "D.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void D_free_fields(struct D *this)
{
				}

static void D_free(struct D *this)
{
	--this->_D_refs;
	if (this->_D_refs < 1)
	{
		D_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z18fieldInitializer10EV()	{
/* D.vdmrt 14:28 */
TVP ret_11 = _Z1BE1CA1CA(NULL, vdmClone(g_D_a1), vdmClone(g_D_a2))
;

ret_11->id = 1;

return ret_11;
}



 static  TVP _Z17fieldInitializer9EV()	{
/* D.vdmrt 13:29 */
TVP ret_12 = _Z1AEV(NULL)
;

ret_12->id = 2;

return ret_12;
}



 static  TVP _Z17fieldInitializer8EV()	{
/* D.vdmrt 12:29 */
TVP ret_13 = _Z1AEV(NULL)
;

ret_13->id = 3;

return ret_13;
}



 static  TVP _Z17fieldInitializer7EV()	{

TVP ret_14 = newInt(3)
;

return ret_14;
}



 void cpu2_init()	{

return ;
}



 void D_const_init()	{

numFields_4 = _Z17fieldInitializer7EV();

return ;
}



 void D_const_shutdown()	{

vdmFree(numFields_4);

return ;
}



 void D_static_init()	{

g_D_a1 = _Z17fieldInitializer8EV();

g_D_a2 = _Z17fieldInitializer9EV();

g_D_b = _Z18fieldInitializer10EV();

return ;
}



 void D_static_shutdown()	{

vdmFree(g_D_a1);

vdmFree(g_D_a2);

vdmFree(g_D_b);

return ;
}



 TVP send_bus(int objID, int funID, int supID, int nrArgs, ... )	{

va_list args 
;

va_start(args, nrArgs);

if ( ((objID == 1) || (objID == 3)) )
	
	return bus(objID, funID, supID, nrArgs, args);;
}



 TVP getRes(int objID, int funID, int supID, int nrArgs, TVP args [])	{

if ( objID == 2 )
	
	{

if ( supID == CLASS_ID_A_ID )
	
	return distA(g_D_a2, funID, nrArgs, args);;

if ( supID == CLASS_ID_World_ID )
	
	return distWorld(g_D_a2, funID, nrArgs, args);;
}
;
}



 TVP distA(TVP obj, int funID, int nrArgs, TVP args [])	{

if ( nrArgs == 0 )
	
	return CALL_FUNC(A, A, obj, funID);;

if ( nrArgs == 1 )
	
	return CALL_FUNC(A, A, obj, funID, args[0]);;

if ( nrArgs == 2 )
	
	return CALL_FUNC(A, A, obj, funID, args[0], args[1]);;

if ( nrArgs == 3 )
	
	return CALL_FUNC(A, A, obj, funID, args[0], args[1], args[2]);;
}



 TVP distB(TVP obj, int funID, int nrArgs, TVP args [])	{

if ( nrArgs == 0 )
	
	return CALL_FUNC(B, B, obj, funID);;

if ( nrArgs == 1 )
	
	return CALL_FUNC(B, B, obj, funID, args[0]);;

if ( nrArgs == 2 )
	
	return CALL_FUNC(B, B, obj, funID, args[0], args[1]);;

if ( nrArgs == 3 )
	
	return CALL_FUNC(B, B, obj, funID, args[0], args[1], args[2]);;
}



 TVP distWorld(TVP obj, int funID, int nrArgs, TVP args [])	{

if ( nrArgs == 0 )
	
	return CALL_FUNC(World, World, obj, funID);;

if ( nrArgs == 1 )
	
	return CALL_FUNC(World, World, obj, funID, args[0]);;

if ( nrArgs == 2 )
	
	return CALL_FUNC(World, World, obj, funID, args[0], args[1]);;

if ( nrArgs == 3 )
	
	return CALL_FUNC(World, World, obj, funID, args[0], args[1], args[2]);;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForD  [] ={

{0,0,((VirtualFunctionPointer) _Z1DEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
DCLASS D_Constructor(DCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (DCLASS) malloc(sizeof(struct D));
	}

	if(this_ptr!=NULL)
	{
	
			
		// D init
		this_ptr->_D_id = CLASS_ID_D_ID;
		this_ptr->_D_refs = 0;
		this_ptr->_D_pVTable=VTableArrayForD;

													}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	DCLASS ptr=D_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_D_id, &ptr->_D_refs, (freeVdmClassFunction)&D_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* D.vdmrt 26:8 */
 TVP _Z1DEV(DCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, D);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order
	TVP numFields_4 =  NULL ;
		TVP g_D_a1 =  NULL ;
		TVP g_D_a2 =  NULL ;
		TVP g_D_b =  NULL ;
	
	 bool DM  [] =

{true,false,true,false,}
				
  ;


