/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "intVal.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void IntValue_Initialize(IntValue* pVal)
{
    *pVal = (IntValue) 0;
}
#endif

 
flag IntValue_IsConstraintValid(const IntValue* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;

	return ret;
}

flag IntValue_Equal(const IntValue* pVal1, const IntValue* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag IntValue_Encode(const IntValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? IntValue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeUnConstraintWholeNumber(pBitStrm, *pVal);
    }

	return ret;
}

flag IntValue_Decode(IntValue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, pVal);
	*pErrCode = ret ? 0 : 268435457;

	return ret;
}

