/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "A.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void A_free_fields(struct A *this)
{
}

static void A_free(struct A *this)
{
	--this->_A_refs;
	if (this->_A_refs < 1)
	{
		A_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 
/* A.vdmrt 5:8 */
 static  TVP _Z7productEII(ACLASS this, TVP a, TVP b)	{
/* A.vdmrt 9:9 */
TVP ret_1 = vdmProductGC(a, b, &ret_1)
;
/* A.vdmrt 9:1 */
return ret_1;
}



 void A_const_init()	{

return ;
}



 void A_const_shutdown()	{

return ;
}



 void A_static_init()	{

return ;
}



 void A_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForA  [] ={

{0,0,((VirtualFunctionPointer) _Z7productEII),},
{0,0,((VirtualFunctionPointer) _Z1AEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
ACLASS A_Constructor(ACLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (ACLASS) malloc(sizeof(struct A));
	}

	if(this_ptr!=NULL)
	{
	
			
		//init base World
		World_Constructor((WorldCLASS)CLASS_CAST(this_ptr,A,World));

				
		
		// A init
		this_ptr->_A_id = CLASS_ID_A_ID;
		this_ptr->_A_refs = 0;
		this_ptr->_A_pVTable=VTableArrayForA;

	}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	ACLASS ptr=A_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_A_id, &ptr->_A_refs, (freeVdmClassFunction)&A_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* A.vdmrt 1:7 */
 TVP _Z1AEV(ACLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, A);
}
;

_Z5WorldEV(((WorldCLASS) CLASS_CAST(this, A, World)));

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order



