/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "D.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void D_free_fields(struct D *this)
{
				}

static void D_free(struct D *this)
{
	--this->_D_refs;
	if (this->_D_refs < 1)
	{
		D_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z17fieldInitializer5EV()	{
/* D.vdmrt 14:28 */
TVP ret_5 = _Z1BE1CA1CA(NULL, vdmClone(g_D_a1), vdmClone(g_D_a2))
;

return ret_5;
}



 static  TVP _Z17fieldInitializer4EV()	{
/* D.vdmrt 13:29 */
TVP ret_6 = _Z1AEV(NULL)
;

return ret_6;
}



 static  TVP _Z17fieldInitializer3EV()	{
/* D.vdmrt 12:29 */
TVP ret_7 = _Z1AEV(NULL)
;

return ret_7;
}



 static  TVP _Z17fieldInitializer2EV()	{

TVP ret_8 = newInt(3)
;

return ret_8;
}



 void D_const_init()	{

numFields_2 = _Z17fieldInitializer2EV();

return ;
}



 void D_const_shutdown()	{

vdmFree(numFields_2);

return ;
}



 void D_static_init()	{

g_D_a1 = _Z17fieldInitializer3EV();

g_D_a2 = _Z17fieldInitializer4EV();

g_D_b = _Z17fieldInitializer5EV();

return ;
}



 void D_static_shutdown()	{

vdmFree(g_D_a1);

vdmFree(g_D_a2);

vdmFree(g_D_b);

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForD  [] ={

{0,0,((VirtualFunctionPointer) _Z1DEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
DCLASS D_Constructor(DCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (DCLASS) malloc(sizeof(struct D));
	}

	if(this_ptr!=NULL)
	{
	
			
		// D init
		this_ptr->_D_id = CLASS_ID_D_ID;
		this_ptr->_D_refs = 0;
		this_ptr->_D_pVTable=VTableArrayForD;

													}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	DCLASS ptr=D_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_D_id, &ptr->_D_refs, (freeVdmClassFunction)&D_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* D.vdmrt 26:8 */
 TVP _Z1DEV(DCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, D);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order
	TVP numFields_2 =  NULL ;
		TVP g_D_a1 =  NULL ;
		TVP g_D_a2 =  NULL ;
		TVP g_D_b =  NULL ;
	


