/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.3-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#ifndef CLASSES_D_H_
#define CLASSES_D_H_

#define VDM_CG

#include "Vdm.h"

//include types used in the class
#include "A.h"
#include "B.h"
#include "D.h"


/* -------------------------------
 *
 * Quotes
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * values / global const
 *
 --------------------------------- */ 
 
extern TVP numFields_2;
extern TVP g_D_a1;
extern TVP g_D_a2;
extern TVP g_D_b;


/* -------------------------------
 *
 * The class
 *
 --------------------------------- */ 
 

//class id
#define CLASS_ID_D_ID 2

#define DCLASS struct D*

// The vtable ids
#define CLASS_D__Z1DEV 0

struct D
{
	
/* Definition of Class: 'D' */
	VDM_CLASS_BASE_DEFINITIONS(D);
	 
	VDM_CLASS_FIELD_DEFINITION(D,numFields);

};


/* -------------------------------
 *
 * Constructors
 *
 --------------------------------- */ 
 

	/* D.vdmrt 26:8 */
	TVP _Z1DEV(DCLASS this_);


/* -------------------------------
 *
 * public access functions
 *
 --------------------------------- */ 
 
	void D_const_init();
	void D_const_shutdown();
	void D_static_init();
	void D_static_shutdown();


/* -------------------------------
 *
 * Internal
 *
 --------------------------------- */ 
 

void D_free_fields(DCLASS);
DCLASS D_Constructor(DCLASS);



#endif /* CLASSES_D_H_ */