name: Java CI with Maven

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]



jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: Maven Build
      run: mvn compile
    - name: Maven Test
      run: mvn test
